name: Release

on:
  push:
    tags:
      - '*'

jobs:
  call-release-workflow:
    uses: inovacc/workflows/.github/workflows/reusable-go-release.yml@main
    with:
      run-release: true
      library-mode: true
    permissions:
      contents: write
    secrets: inherit
